version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: quote-request-backend-dev
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - documents:/app/documents
      - lancedb-data:/app/lancedb-data
      - ./auto-request-form.docx:/app/auto-request-form.docx
      - ./home-quote-request-form.docx:/app/home-quote-request-form.docx
      - ./specialty-quote-request-form.docx:/app/specialty-quote-request-form.docx
    environment:
      - DATABASE_URL=sqlite:///./quoterequest.db
      - SECRET_KEY=dev_secret_key_not_for_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALLOWED_ORIGINS=http://localhost:${FRONTEND_PORT},http://localhost:80,http://localhost,https://quote-request-fresh-ao4t9nrjp-jakenelwoods-projects.vercel.app
      - LANCEDB_URI=/app/lancedb-data
      - BACKEND_PORT=${BACKEND_PORT}
      - HOST=0.0.0.0
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: python run.py

  # Frontend service for development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.debug
    container_name: quote-request-frontend-dev
    restart: "no"
    volumes:
      - ./frontend:/app
      - documents:/app/documents
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}/api
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=${FRONTEND_PORT}
      - NODE_ENV=development
      - PORT=3000
    command: node start-debug.js

volumes:
  documents:
    driver: local
  lancedb-data:
    driver: local
