version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: quote-request-backend-dev
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - documents:/app/documents
    environment:
      - DATABASE_URL=sqlite:///./quoterequest.db
      - SECRET_KEY=dev_secret_key_not_for_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80,http://localhost
    ports:
      - "8000:8000"
    command: python run.py

  # Frontend service for development (uses React's development server)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: quote-request-frontend-dev
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  documents: # Volume for storing generated documents 